<?php
namespace webrise1\filemanager;
use function Clue\StreamFilter\append;
use webrise1\filemanager\models\Folder;
use yii\base\Module as BaseModule;
use Yii;
class Module extends BaseModule
{
    const MODULE_UPLOADS_FOLDER_NAME='extension_filemanager';
    const DEPENDENT_MODULES=[
      'pdfgenerator'
    ];
    public $modelsUsingFileSnippets;
    public $defaultModelsUsingFileSnippets=[

    ];
    public $controllerNamespace = 'webrise1\filemanager\controllers';
    public $folders;
    public $uploadsDir;
//    public $defaultFolders=[
//
//        'project'=>[
//            'title'=>'Главная',
//            'images'=>[
//                'png'=>['title'=>'']
//            ],
//        ],
//        ['path'=>'project', 'title'=>'Главная'],
//        ['path'=>'project/images', 'title'=>'Изображения'],
//        ['path'=>'project/images/png', 'title'=>'Изображения(PNG)'],
//        ['path'=>'project/images/jpg', 'title'=>'Изображения(JPG)'],
//        ['path'=>'project/documents', 'title'=>'Документы'],
//    ];
    public $SchemaFolders;
    public $defaultFolders=[
         [
            'title'=>'Главная',
            'folderName'=>'project',
            'childs'=>[
                [
                    'title'=>'Изображения',
                    'folderName'=>'images',
                ],
                [
                    'title'=>'Документы',
                    'folderName'=>'document'
                ],
            ]
        ],

    ];
    public $addFolders;

    public function init()
    {
        if(!$this->modelsUsingFileSnippets)
            $this->modelsUsingFileSnippets=[];
        $this->SchemaFolders=$this->defaultFolders;
        $this->modelsUsingFileSnippets=array_merge($this->modelsUsingFileSnippets, $this->defaultModelsUsingFileSnippets);
        foreach(self::DEPENDENT_MODULES as $moduleName){
            if($module=Yii::$app->getModule($moduleName)){
                array_push($this->SchemaFolders, $module::SchemaFolders);
                $this->modelsUsingFileSnippets=array_merge($this->modelsUsingFileSnippets,$module::modelsUsingFileSnippets);
            }
        }

        self::initFolders($this->SchemaFolders);
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function initFolders($foldersSchema,&$parent=null){
        foreach($foldersSchema as $folderSchema){
            $folder=new Folder();
            $folder->title=$folderSchema['title'];
            $folder->folderName=$folderSchema['folderName'];
            $folder->pathNS=$folderSchema['folderName'];
            $folder->path=$folderSchema['folderName'];
            if($parent){
                $parent->childs[]=$folder;
                $folder->parent=$parent;
                $folder->pathNS=$parent->pathNS.'.'.$folder->pathNS;
                $folder->path=$parent->path.'/'.$folder->path;
            }
            $this->folders[$folder->pathNS]=$folder;
            if($folderSchema['childs']){
                $this->initFolders($folderSchema['childs'],$folder);
            }
        }



    }
}